### ISSUE TITLE
Add a slight background blur affect while the modal is active 

### ISSUE THREAD

**Issue by mirazxmondal** [mirazxmondal/Yum-Yum#10]
### Add a slight background blur affect while the modal is active on `about.html` page

![image](https://github.com/mirazxmondal/Yum-Yum/assets/89645073/28305f93-2c1f-41e0-aacc-af95d648be82)

**Comment by mirazxmondal** [comment]
@Nabzoku would you like to work on this issue?

**Comment by Nabzoku** [comment]
I'll check it when I find some free time

**Comment by mirazxmondal** [comment]
Sure!

**Comment by Nabzoku** [comment]
It's done #11

**Comment by mirazxmondal** [comment]
Cool
