### ISSUE TITLE
Navbar layout fix

### ISSUE THREAD

**Issue by mirazxmondal** [mirazxmondal/Yum-Yum#13]
####  Navbar layout needs to be changed. The "Yum Yum logo" should be in the right with `margin-left: 10.5%;` margin and in the middle `Home`, `Explore` and `About` tab should be placed and in the left with `margin-right: 10.5%;`  `Login | Register` and the `Cart` image should be placed 

![navbar](https://github.com/mirazxmondal/Yum-Yum/assets/89645073/16987b0d-4815-4197-a064-a0b94898a675)

**Comment by sohaibaumer** [comment]
can i get assigned?

**Comment by mirazxmondal** [comment]
Go ahead!
