### ISSUE TITLE
Fix loginregister page navbar

### ISSUE THREAD

**Issue by mirazxmondal** [mirazxmondal/Yum-Yum#4]
### **CURRENT NAVBAR** 
![Screenshot (289)](https://user-images.githubusercontent.com/89645073/234338169-dcfa2596-c57f-4e6c-89fb-1a57538f7615.png)

### **THE NAVBAR SHOULD BE** 
![Screenshot (288)](https://user-images.githubusercontent.com/89645073/234338228-d672de96-cdc5-4bdb-943a-39b3ed12113e.png)

**Comment by alchuu00** [comment]
Hi @mirazxmondal, can you assign me this issue please

**Comment by mirazxmondal** [comment]
Sure, all the best! @alchuu00

**Comment by alchuu00** [comment]
@mirazxmondal when I open the website, the navbar is displayed correctly, the login/register button looks good. Can you please explain in detail what needs to be fixed? thank you

**Comment by mirazxmondal** [comment]
The problem is that in all the pages for example in [Home](https://github.com/mirazxmondal/Yum-Yum/blob/main/index.html), [Explore](https://github.com/mirazxmondal/Yum-Yum/blob/main/Assets/HTML/explore.html), [About](https://github.com/mirazxmondal/Yum-Yum/blob/main/Assets/HTML/about.html) the Navbar is like this
![original-navbar](https://user-images.githubusercontent.com/89645073/234914495-3b9daf9b-701c-46a8-a356-fad22800ca0e.png)

However, in the [Login Register](https://github.com/mirazxmondal/Yum-Yum/blob/main/Assets/HTML/loginregister.html) page the Navbar is showing something like this with the same CSS styling applied 
![bug-navbar](https://user-images.githubusercontent.com/89645073/234914789-7fe49238-5670-4846-a747-7d65bd60ca22.png)

As you can see the Login/Register button has been enlarged. That's the bug and could you clarify what's your screen size because this bug has occurred for the 15.6” inch screen size

**Comment by alchuu00** [comment]
@mirazxmondal  Okay now I see the bug. I was on a 1366 x 768 resolution before, now I see it on 1920 x 1080. I'll start working on it now

**Comment by mirazxmondal** [comment]
@alchuu00 Okay, after which please raise a PR!

**Comment by alchuu00** [comment]
@mirazxmondal I fixed the bug and opened pull request
