### ISSUE TITLE
Add modal in blog page 

### ISSUE THREAD

**Issue by mirazxmondal** [mirazxmondal/Yum-Yum#8]
### In the `about.html` add modal to the `Find out more` button the modal border should be `border: 5px solid #ff789c;` 

![blog](https://github.com/mirazxmondal/Yum-Yum/assets/89645073/d166eef5-f0fc-4bc1-8642-f0907e83c5ff)

**Comment by Nabzoku** [comment]
#9 Hope this does the job.

**Comment by mirazxmondal** [comment]
Yes it did!
